export const APP_SECTION_GROUPS = [
  {
    name: 'General',
    sections: [
      { path: '/dashboard/profile', label: 'Profile' },
    ],
  },
  {
    name: 'Customers',
    sections: [
      { path: '/dashboard/front-desk', label: 'Front Desk (Check In/Out)' },
      { path: '/dashboard/customers', label: 'All Customers' },
      { path: '/dashboard/loyalty', label: 'Loyalty Customers' },
    ],
  },
  {
    name: 'Restaurant',
    sections: [
      { path: '/dashboard', label: 'Dashboard' },
      { path: '/dashboard/restaurant-analytics', label: 'Restaurant Analytics' },
      { path: '/dashboard/billing', label: 'Restaurant Billing' },
      { path: '/dashboard/menu-management', label: 'Menu Management' },
      { path: '/dashboard/table-management', label: 'Table Management' },
      { path: '/dashboard/menu-settings', label: 'Menu Section Settings' },
      { path: '/dashboard/restaurant-settings', label: 'Restaurant Settings' },
    ],
  },
  {
    name: 'Inventory',
    sections: [
      { path: '/dashboard/inventory-management/warehouses', label: 'Manage Store' },
      { path: '/dashboard/inventory-management/add-item', label: 'Add New Item' },
      { path: '/dashboard/inventory-requests', label: 'MRN Requests' },
      { path: '/dashboard/inventory-requests/history', label: 'MRN Approvals' },
      { path: '/dashboard/inventory-cash-requests', label: 'Cash Requests' },
      { path: '/dashboard/inventory-cash-approvals', label: 'Cash Approvals' },
      { path: '/dashboard/purchase-orders', label: 'Purchase Orders' },
      { path: '/dashboard/purchase-orders/approvals', label: 'PO Approvals' },
      { path: '/dashboard/inventory-stock-overview', label: 'Stock Overview' },
      { path: '/dashboard/inventory-management/grn', label: 'GRN (Stock In)' },
      { path: '/dashboard/inventory-management', label: 'Manage Items' },
      { path: '/dashboard/inventory-management/stock-usage', label: 'Stock Usage' },
      { path: '/dashboard/inventory-management/expired-damaged', label: 'Expired & Damaged' },
      { path: '/dashboard/inventory-management/transaction-log', label: 'Transaction Log' },
      { path: '/dashboard/inventory-reports', label: 'Inventory Reports' },
    ],
  },
  {
    name: 'Kitchen',
    sections: [
      { path: '/dashboard/kitchen/orders', label: 'Kitchen Orders' },
      { path: '/dashboard/kitchen/inventory-requests', label: 'Request Stock' },
      { path: '/dashboard/kitchen/stock-usage', label: 'Stock Usage & Damage' },
    ],
  },
  {
    name: 'Rooms & Bookings',
    sections: [
      { path: '/dashboard/room-management', label: 'Room Management' },
      { path: '/dashboard/reservations', label: 'Reservation Management' },
      { path: '/dashboard/experience-inquiries', label: 'Experience Inquiries' },
      { path: '/dashboard/inquiries', label: 'Inquiries' },
      { path: '/dashboard/buffet-bookings', label: 'Buffet Bookings' },
      { path: '/dashboard/buffet-packages', label: 'Buffet Packages' },
    ],
  },
  {
    name: 'Chalet Booking',
    sections: [
      { path: '/dashboard/chalet/bookings', label: 'Chalet Bookings' },
      { path: '/dashboard/chalet/rooms', label: 'Chalet Rooms' },
      { path: '/dashboard/chalet/rates', label: 'Room Rates & Packages' },
    ],
  },
  {
    name: 'Financial',
    sections: [
      { path: '/dashboard/accounting', label: 'Accounting' },
      { path: '/dashboard/accounting/daily-workers-finance', label: 'Finance Requests' },
      { path: '/dashboard/accounting/inventory-cash', label: 'Inventory Cash' },
      { path: '/dashboard/expenses', label: 'Other Expenses' },
      { path: '/dashboard/other-incomes', label: 'Other Incomes' },
      { path: '/dashboard/reports', label: 'Financial Reports' },
    ],
  },
  {
    name: 'Services',
    sections: [
      { path: '/dashboard/services/laundry', label: 'Laundry Income' },
      { path: '/dashboard/services/transport', label: 'Transport & Excursion' },
      { path: '/dashboard/services/spa', label: 'Spa/Pool Income' },
    ],
  },
  {
    name: 'HRMS',
    sections: [
      { path: '/dashboard/hrms/dashboard', label: 'HRMS Dashboard' },
      { path: '/dashboard/hrms/employees', label: 'Employees' },
      { path: '/dashboard/hrms/leaves', label: 'Leaves' },
      { path: '/dashboard/hrms/leave-schemes', label: 'Leave Schemes' },
      { path: '/dashboard/hrms/leave-approvals', label: 'Leave Approvals' },
      { path: '/dashboard/hrms/manager-leave-approvals', label: 'Manager Leave Approvals' },
      { path: '/dashboard/hrms/working-calendar', label: 'Working Calendar' },
      { path: '/dashboard/hrms/reports', label: 'Daily Reports' },
      { path: '/dashboard/hrms/payroll', label: 'Payroll' },
      { path: '/dashboard/hrms/payroll-summary', label: 'Payroll Summary' },
      { path: '/dashboard/hrms/apit-settings', label: 'APIT Tax Settings' },
      { path: '/dashboard/hrms/payslip', label: 'My Payslips' },
      { path: '/dashboard/hrms/allowance-types', label: 'Allowance Types' },
      { path: '/dashboard/hrms/job-titles', label: 'Job Titles' },
      { path: '/dashboard/hrms/attendance', label: 'Attendance' },
      { path: '/dashboard/hrms/daily-workers', label: 'Daily Workers' },
      { path: '/dashboard/hrms/daily-workers/requests', label: 'Daily Worker Requests' },
      { path: '/dashboard/hrms/ot', label: 'My OT Requests' },
      { path: '/dashboard/hrms/manager-ot-approvals', label: 'Manager OT Approvals' },
      { path: '/dashboard/hrms/ot-approvals', label: 'OT Approvals' },
      { path: '/dashboard/hrms/ot-settings', label: 'OT Settings' },
      { path: '/dashboard/settings/roles', label: 'Role Permissions' },
      { path: '/dashboard/hrms/petty-cash', label: 'My Petty Cash' },
      { path: '/dashboard/hrms/petty-cash-approvals', label: 'Petty Cash Approvals' },
      { path: '/dashboard/hrms/petty-cash-accounts', label: 'Petty Cash (Accounts)' },
    ],
  },
  {
    name: 'Other',
    sections: [
      { path: '/dashboard/activities', label: 'Activities' },
      { path: '/dashboard/experiences', label: 'Experiences' },
      { path: '/dashboard/blogs', label: 'Blog Management' },
    ],
  },
];

// Default permissions for each role — used when creating a new employee
export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  admin: APP_SECTION_GROUPS.flatMap(g => g.sections.map(s => s.path)),
  waiter: [
    '/dashboard/profile',
    '/dashboard',
    '/dashboard/billing',
    '/dashboard/hrms/leaves',
    '/dashboard/hrms/reports',
    '/dashboard/hrms/attendance',
    '/dashboard/hrms/ot',
    '/dashboard/hrms/manager-ot-approvals',
  ],
  kitchen: [
    '/dashboard/profile',
    '/dashboard',
    '/dashboard/kitchen/orders',
    '/dashboard/kitchen/inventory-requests',
    '/dashboard/kitchen/stock-usage',
    '/dashboard/hrms/leaves',
    '/dashboard/hrms/reports',
    '/dashboard/hrms/attendance',
    '/dashboard/hrms/ot',
    '/dashboard/hrms/manager-ot-approvals',
  ],
  payment: [
    '/dashboard/profile',
    '/dashboard',
    '/dashboard/billing',
    '/dashboard/reports',
    '/dashboard/accounting/daily-workers-finance',
    '/dashboard/accounting/finance-requests-report',
    '/dashboard/hrms/leaves',
    '/dashboard/hrms/reports',
    '/dashboard/hrms/attendance',
    '/dashboard/hrms/ot',
    '/dashboard/hrms/manager-ot-approvals',
  ],
  temporary: [
    '/dashboard/profile',
    '/dashboard/hrms/attendance',
  ],
};
