'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChefHat, RefreshCw } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type KitchenEvent = { id:string; name:string; starts_at:string; ends_at:string|null; venue:string|null; capacity:number; kitchen_status:string; kitchen_completed_by_name:string|null; kitchen_completed_at:string|null; food:Array<{id:string;name:string;quantity:number;unit:string}> };

export default function KitchenEventsPage() {
  const router=useRouter(); const supabase=useMemo(()=>createClient(),[]); const {toast}=useToast();
  const [events,setEvents]=useState<KitchenEvent[]>([]); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('events').select('id,name,starts_at,ends_at,venue,capacity,kitchen_status,kitchen_completed_by_name,kitchen_completed_at,food:event_food_items(id,name,quantity,unit)').eq('approval_status','approved').neq('status','cancelled').order('starts_at');setLoading(false);if(error)return toast({variant:'destructive',title:'Could not load kitchen events',description:error.message});setEvents((data||[]) as unknown as KitchenEvent[]);},[supabase,toast]);
  useEffect(()=>{void load();const channel=supabase.channel('kitchen-events-list').on('postgres_changes',{event:'*',schema:'public',table:'events'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'event_food_items'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load,supabase]);
  const active=events.filter(event=>event.kitchen_status!=='completed'&&event.food.length>0).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime());
  const completed=events.filter(event=>event.kitchen_status==='completed'&&event.food.length>0).sort((a,b)=>new Date(b.starts_at).getTime()-new Date(a.starts_at).getTime());
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ChefHat className="h-6 w-6"/>Event Food Requirements</h1><p className="text-sm text-muted-foreground">Select an approved event to view its complete kitchen requirements.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</Button></div><Tabs defaultValue="active"><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="active">Active ({active.length})</TabsTrigger><TabsTrigger value="completed">Completed ({completed.length})</TabsTrigger></TabsList><TabsContent value="active"><EventTable rows={active} empty={loading?'Loading events…':'No active approved event food requirements.'} onView={id=>router.push(`/dashboard/kitchen/events/${id}`)}/></TabsContent><TabsContent value="completed"><EventTable rows={completed} empty="No completed kitchen events." onView={id=>router.push(`/dashboard/kitchen/events/${id}`)}/></TabsContent></Tabs></div>;
}

function EventTable({rows,empty,onView}:{rows:KitchenEvent[];empty:string;onView:(id:string)=>void}) { return <Card><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Date & time</TableHead><TableHead>Venue</TableHead><TableHead>Guests</TableHead><TableHead>Food requirements</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.length===0?<TableRow><TableCell colSpan={7} className="h-28 text-center text-muted-foreground">{empty}</TableCell></TableRow>:rows.map(event=><TableRow key={event.id} className="cursor-pointer hover:bg-muted/50" onClick={()=>onView(event.id)}><TableCell className="font-medium">{event.name}</TableCell><TableCell className="whitespace-nowrap">{new Date(event.starts_at).toLocaleDateString()}<div className="text-xs text-muted-foreground">{new Date(event.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}{event.ends_at&&` – ${new Date(event.ends_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}</div></TableCell><TableCell>{event.venue||'—'}</TableCell><TableCell>{event.capacity}</TableCell><TableCell><span className="font-semibold">{event.food.length} items</span><div className="text-xs text-muted-foreground">{event.food.reduce((sum,item)=>sum+Number(item.quantity),0).toLocaleString()} total quantity</div></TableCell><TableCell><Badge className={event.kitchen_status==='completed'?'bg-green-600':'bg-amber-500'}>{event.kitchen_status.replaceAll('_',' ')}</Badge>{event.kitchen_completed_by_name&&<div className="mt-1 text-xs text-muted-foreground">by {event.kitchen_completed_by_name}</div>}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={click=>{click.stopPropagation();onView(event.id);}}>View Details</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>; }
