'use client';
import { useCallback,useEffect,useState } from 'react';
import { format } from 'date-fns';
import { ArrowRightLeft,Loader2,RefreshCw,WalletCards } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Badge } from '@/components/ui/badge';import { Button } from '@/components/ui/button';import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card';import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog';import { Input } from '@/components/ui/input';import { Label } from '@/components/ui/label';import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';import { Textarea } from '@/components/ui/textarea';
const money=(v:number)=>`LKR ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function AccountCollectionView({endpoint='/api/admin/services-account',title='Services Account',description='Cash and card income from Laundry, Transport/Excursions, and Spa/Pool.',entityLabel='Services'}:{endpoint?:string;title?:string;description?:string;entityLabel?:string}){const{toast}=useToast();const[data,setData]=useState<any>({summary:{},by_service:{},transfers:[],accounts:[],settings:{}});const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[accountId,setAccountId]=useState('');const[amount,setAmount]=useState('');const[notes,setNotes]=useState('');const[cardAccountId,setCardAccountId]=useState('');const[savingCard,setSavingCard]=useState(false);
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(endpoint,{cache:'no-store'});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||`Failed to load ${entityLabel.toLowerCase()} account.`);setData(d);setCardAccountId(d.settings?.card_account_id||'');}catch(e:any){toast({variant:'destructive',title:`${entityLabel} Account Unavailable`,description:e.message});}finally{setLoading(false);}},[endpoint,entityLabel,toast]);useEffect(()=>{void load();},[load]);
const saveCard=async()=>{if(!cardAccountId)return;setSavingCard(true);try{const r=await fetch(endpoint,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({card_account_id:cardAccountId})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error);toast({title:'Card Payment Account Saved',description:`Future ${entityLabel.toLowerCase()} card transactions will post automatically.`});await load();}catch(e:any){toast({variant:'destructive',title:'Save Failed',description:e.message});}finally{setSavingCard(false);}};
const transfer=async()=>{const value=Number(amount);if(!accountId||value<=0||value>Number(data.summary.available_cash||0))return;setSaving(true);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account_id:accountId,amount:value,notes})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error);toast({title:`${entityLabel} Cash Transferred`,description:`${money(value)} posted to Accounting.`});setOpen(false);setAmount('');setNotes('');setAccountId('');await load();}catch(e:any){toast({variant:'destructive',title:'Transfer Failed',description:e.message});}finally{setSaving(false);}};const s=data.summary||{};
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-3xl font-bold"><WalletCards className="h-7 w-7 text-primary"/>{title}</h1><p className="mt-1 text-muted-foreground">{description}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</Button><Button onClick={()=>setOpen(true)} disabled={loading||Number(s.available_cash||0)<=0}><ArrowRightLeft className="mr-2 h-4 w-4"/>Transfer Cash</Button></div></div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{l:'Available Cash',v:s.available_cash,c:'text-emerald-600',x:'Ready to transfer'},{l:'Cash Collected',v:s.cash_total,c:'text-slate-900',x:`${s.cash_count||0} payments`},{l:'Cash Transferred',v:s.transferred_cash,c:'text-blue-600',x:'Posted to Accounting'},{l:'Card Payments',v:s.card_total,c:'text-violet-600',x:`${s.card_count||0} payments`}].map(x=><Card key={x.l}><CardContent className="p-5"><p className="text-xs font-bold uppercase text-muted-foreground">{x.l}</p><p className={`mt-2 text-2xl font-black ${x.c}`}>{loading?'—':money(x.v)}</p><p className="text-xs text-muted-foreground">{x.x}</p></CardContent></Card>)}</div>
<div className="grid gap-4 md:grid-cols-3">{Object.entries(data.by_section||data.by_service||{}).map(([name,value])=>{const detail=value as any;const total=typeof detail==='object'?detail.total:detail;return <Card key={name}><CardContent className="p-4"><p className="text-xs font-bold uppercase text-muted-foreground">{name.replaceAll('_',' ')}</p><p className="mt-1 text-xl font-black">{money(Number(total))}</p>{typeof detail==='object'&&<div className="mt-2 flex gap-4 text-xs"><span className="text-emerald-700">Cash: {money(detail.cash)}</span><span className="text-violet-700">Card: {money(detail.card)}</span></div>}</CardContent></Card>})}</div>
<Card><CardHeader><CardTitle className="text-base">{entityLabel} Card Payment Account</CardTitle><CardDescription>Card payments post directly to this Accounting account.</CardDescription></CardHeader><CardContent><div className="flex max-w-2xl flex-col gap-3 sm:flex-row"><Select value={cardAccountId} onValueChange={setCardAccountId}><SelectTrigger className="flex-1"><SelectValue placeholder="Select card destination account"/></SelectTrigger><SelectContent>{data.accounts.map((a:any)=><SelectItem key={a.id} value={a.id}>{a.name} · {a.type.replaceAll('_',' ')} · {money(a.current_balance)}</SelectItem>)}</SelectContent></Select><Button onClick={saveCard} disabled={!cardAccountId||savingCard}>{savingCard&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Save Card Account</Button></div></CardContent></Card>
{data.transactions&&<Card><CardHeader><CardTitle className="text-base">Payment Transactions</CardTitle><CardDescription>Cash and card transactions recorded for each {entityLabel.toLowerCase()}.</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>{entityLabel}</TableHead><TableHead>Receipt / Payer</TableHead><TableHead>Method</TableHead><TableHead>Account status</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{data.transactions.map((r:any)=><TableRow key={r.id}><TableCell>{format(new Date(r.paid_at),'dd MMM yyyy HH:mm')}</TableCell><TableCell className="font-medium">{r.event?.name||'—'}</TableCell><TableCell>{r.receipt_number}<div className="text-xs text-muted-foreground">{r.payer_name}</div></TableCell><TableCell><Badge variant="outline">{r.payment_method}</Badge><div className="mt-1 text-xs capitalize text-muted-foreground">{r.payment_type}</div></TableCell><TableCell>{r.payment_method==='cash'&&!r.account_transaction_id?'Event Cash':r.account?.name||'Not posted'}<div className={`text-xs ${r.account_transaction_id?'text-green-600':'text-amber-600'}`}>{r.account_transaction_id?'Posted to Accounting':'Awaiting cash transfer'}</div></TableCell><TableCell className={`text-right font-bold ${r.payment_type==='refund'?'text-red-600':'text-emerald-600'}`}>{r.payment_type==='refund'?'-':''}{money(r.amount)}</TableCell></TableRow>)}{!loading&&data.transactions.length===0&&<TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No payment transactions yet.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>}
<Card><CardHeader><CardTitle className="text-base">Cash Transfer History</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Account</TableHead><TableHead>Notes</TableHead><TableHead>By</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{data.transfers.map((r:any)=><TableRow key={r.id}><TableCell>{format(new Date(r.created_at),'dd MMM yyyy HH:mm')}</TableCell><TableCell>{r.account?.name||'—'}<Badge variant="outline" className="ml-2 text-[9px]">{r.account?.type}</Badge></TableCell><TableCell>{r.notes||'—'}</TableCell><TableCell>{r.user?.name||'—'}</TableCell><TableCell className="text-right font-bold text-emerald-600">{money(r.amount)}</TableCell></TableRow>)}{!loading&&data.transfers.length===0&&<TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">No cash transfers yet.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>
<Dialog open={open} onOpenChange={v=>!saving&&setOpen(v)}><DialogContent><DialogHeader><DialogTitle>Transfer {entityLabel} Cash</DialogTitle><DialogDescription>Available: <strong>{money(s.available_cash)}</strong></DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Destination account *</Label><Select value={accountId} onValueChange={setAccountId}><SelectTrigger><SelectValue placeholder="Select account"/></SelectTrigger><SelectContent>{data.accounts.map((a:any)=><SelectItem key={a.id} value={a.id}>{a.name} · {money(a.current_balance)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Amount *</Label><Input type="number" min="0.01" max={s.available_cash} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="space-y-2"><Label>Notes</Label><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={transfer} disabled={saving||!accountId||Number(amount)<=0||Number(amount)>Number(s.available_cash||0)}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Confirm Transfer</Button></DialogFooter></DialogContent></Dialog></div>}

export default function ServicesAccountPage(){return <AccountCollectionView/>;}
