'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, CheckCircle2, ChefHat, Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { useUserContext } from '@/context/user-context';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type KitchenEvent = { id:string; name:string; event_type:string; starts_at:string; ends_at:string|null; venue:string|null; capacity:number; notes:string|null; owner_name:string|null; owner_mobile:string|null; contact_person:string|null; contact_telephone:string|null; kitchen_status:string; kitchen_completed_by_name:string|null; kitchen_completed_at:string|null; food:Array<{id:string;name:string;category:string;quantity:number;unit:string;dietary_notes:string|null}> };

export default function KitchenEventDetailsPage() {
  const {id}=useParams<{id:string}>(); const router=useRouter(); const supabase=useMemo(()=>createClient(),[]); const {toast}=useToast(); const {user}=useUserContext();
  const [event,setEvent]=useState<KitchenEvent|null>(null); const [loading,setLoading]=useState(true); const [confirmOpen,setConfirmOpen]=useState(false); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('events').select('id,name,event_type,starts_at,ends_at,venue,capacity,notes,owner_name,owner_mobile,contact_person,contact_telephone,kitchen_status,kitchen_completed_by_name,kitchen_completed_at,food:event_food_items(id,name,category,quantity,unit,dietary_notes)').eq('id',id).eq('approval_status','approved').single();setLoading(false);if(error)return toast({variant:'destructive',title:'Could not load event requirements',description:error.message});setEvent(data as unknown as KitchenEvent);},[id,supabase,toast]);
  useEffect(()=>{void load();},[load]);
  const complete=async()=>{if(!event||!user)return;setSaving(true);const {error}=await supabase.from('events').update({kitchen_status:'completed',kitchen_completed_by:user.id,kitchen_completed_by_name:user.name||user.email||'Kitchen user',kitchen_completed_at:new Date().toISOString()}).eq('id',event.id);setSaving(false);if(error)return toast({variant:'destructive',title:'Could not complete event',description:error.message});toast({title:'Kitchen requirements completed',description:`${event.name} moved to the Completed list.`});router.push('/dashboard/kitchen/events');};
  if(loading)return <Card><CardContent className="py-16 text-center text-muted-foreground">Loading event requirements…</CardContent></Card>;
  if(!event)return <Card><CardContent className="py-16 text-center text-muted-foreground">Event not found or not approved.</CardContent></Card>;
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><Button variant="ghost" className="mb-2 px-0" onClick={()=>router.push('/dashboard/kitchen/events')}><ArrowLeft className="mr-2 h-4 w-4"/>Back to events</Button><h1 className="flex items-center gap-2 text-2xl font-bold"><ChefHat className="h-6 w-6"/>{event.name}</h1><p className="text-sm text-muted-foreground">Full event food and kitchen requirements.</p></div>{event.kitchen_status==='completed'?<Badge className="w-fit bg-green-600 px-3 py-1.5">Completed</Badge>:<Button className="bg-green-600 hover:bg-green-700" onClick={()=>setConfirmOpen(true)}><CheckCircle2 className="mr-2 h-4 w-4"/>Mark Event Complete</Button>}</div>
  <Card><CardHeader><CardTitle className="text-base">Event Information</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Date" value={new Date(event.starts_at).toLocaleDateString()}/><Info label="Time" value={`${new Date(event.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}${event.ends_at?` – ${new Date(event.ends_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:''}`}/><Info label="Venue" value={event.venue}/><Info label="Expected guests" value={`${event.capacity}`}/><Info label="Event owner" value={event.owner_name}/><Info label="Owner mobile" value={event.owner_mobile}/><Info label="Contact person" value={event.contact_person||event.owner_name}/><Info label="Contact telephone" value={event.contact_telephone||event.owner_mobile}/>{event.notes&&<div className="sm:col-span-2 lg:col-span-4"><Info label="Event notes" value={event.notes}/></div>}{event.kitchen_status==='completed'&&<div className="sm:col-span-2 lg:col-span-4 rounded-md bg-green-50 p-3 text-sm dark:bg-green-950/30">Completed by <strong>{event.kitchen_completed_by_name||'Kitchen user'}</strong> on {event.kitchen_completed_at?new Date(event.kitchen_completed_at).toLocaleString():'—'}</div>}</CardContent></Card>
  <div className="grid gap-3 sm:grid-cols-2"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Food items</p><p className="mt-1 text-2xl font-bold">{event.food.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Total planned quantity</p><p className="mt-1 flex items-center gap-2 text-2xl font-bold"><Users className="h-5 w-5"/>{event.food.reduce((sum,item)=>sum+Number(item.quantity),0).toLocaleString()}</p></CardContent></Card></div>
  <Card><CardHeader><CardTitle className="text-base">Food Requirements</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Category</TableHead><TableHead>Food item</TableHead><TableHead className="text-right">Quantity to prepare</TableHead><TableHead>Dietary / preparation notes</TableHead></TableRow></TableHeader><TableBody>{event.food.map(item=><TableRow key={item.id}><TableCell><Badge variant="outline">{item.category}</Badge></TableCell><TableCell className="font-medium">{item.name}</TableCell><TableCell className="text-right text-xl font-bold">{Number(item.quantity).toLocaleString()} <span className="text-sm font-normal text-muted-foreground">{item.unit}</span></TableCell><TableCell>{item.dietary_notes||'—'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Complete Kitchen Requirements?</DialogTitle></DialogHeader><div className="rounded-lg border border-green-200 bg-green-50 p-4 dark:border-green-900 dark:bg-green-950/30"><p className="font-semibold">{event.name}</p><p className="mt-1 text-sm text-muted-foreground">This will move the event from Active to the Completed list. The event and food details will remain available.</p></div><DialogFooter><Button variant="outline" onClick={()=>setConfirmOpen(false)}>Cancel</Button><Button className="bg-green-600 hover:bg-green-700" disabled={saving} onClick={complete}>{saving?'Completing…':'Complete Event'}</Button></DialogFooter></DialogContent></Dialog></div>;
}

function Info({label,value}:{label:string;value:string|null|undefined}) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium whitespace-pre-wrap">{value||'—'}</p></div>; }
