import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { cookies } from 'next/headers';
import { verifyToken } from '@/lib/auth-utils';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
async function auth(){const token=(await cookies()).get('auth_token')?.value;return token?verifyToken(token):null;}
export async function GET(){try{const user=await auth() as any;if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});if(user.role!=='admin')return NextResponse.json({error:'Forbidden'},{status:403});const [incomeRes,transferRes,accountRes,settingRes]=await Promise.all([supabase.from('service_incomes').select('id,amount,date,service_type,payment_method').eq('payment_status','paid'),supabase.from('services_cash_transfers').select('id,amount,notes,created_at,account:accounts(id,name,type),user:users(name)').order('created_at',{ascending:false}).limit(200),supabase.from('accounts').select('id,name,type,current_balance').eq('is_active',true).order('name'),supabase.from('services_account_settings').select('card_account_id').eq('singleton',true).maybeSingle()]);if(incomeRes.error)throw incomeRes.error;if(transferRes.error)throw transferRes.error;if(accountRes.error)throw accountRes.error;if(settingRes.error)throw settingRes.error;const incomes=incomeRes.data||[];const cash=incomes.filter(x=>x.payment_method==='cash');const card=incomes.filter(x=>x.payment_method==='card');const transfers=transferRes.data||[];const cashTotal=cash.reduce((s,x)=>s+Number(x.amount),0);const transferred=transfers.reduce((s,x)=>s+Number(x.amount),0);return NextResponse.json({summary:{cash_total:cashTotal,available_cash:cashTotal-transferred,transferred_cash:transferred,card_total:card.reduce((s,x)=>s+Number(x.amount),0),cash_count:cash.length,card_count:card.length},by_service:incomes.reduce((map:any,row:any)=>{map[row.service_type]=(map[row.service_type]||0)+Number(row.amount);return map;},{}),transfers,accounts:accountRes.data||[],settings:settingRes.data||{card_account_id:null}});}catch(error:any){return NextResponse.json({error:error.message},{status:500});}}
export async function POST(request:Request){try{const user=await auth() as any;if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});if(user.role!=='admin')return NextResponse.json({error:'Forbidden'},{status:403});const {account_id,amount,notes}=await request.json();const value=Number(amount);if(!account_id||!Number.isFinite(value)||value<=0)return NextResponse.json({error:'Valid account and amount are required.'},{status:400});const {data,error}=await supabase.rpc('transfer_services_cash',{p_account_id:account_id,p_amount:value,p_notes:notes||'',p_user_id:user.userId});if(error)throw error;return NextResponse.json({transfer_id:data},{status:201});}catch(error:any){return NextResponse.json({error:error.message},{status:500});}}
export async function PUT(request:Request){try{const user=await auth() as any;if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});if(user.role!=='admin')return NextResponse.json({error:'Forbidden'},{status:403});const {card_account_id}=await request.json();const {data:account}=await supabase.from('accounts').select('id').eq('id',card_account_id).eq('is_active',true).maybeSingle();if(!account)return NextResponse.json({error:'Active account not found.'},{status:404});const {error}=await supabase.from('services_account_settings').upsert({singleton:true,card_account_id,updated_by:user.userId,updated_at:new Date().toISOString()},{onConflict:'singleton'});if(error)throw error;return NextResponse.json({success:true});}catch(error:any){return NextResponse.json({error:error.message},{status:500});}}
